import { IEmployee } from '~/types/IEmployee';

// Array of mock employees
export const MOCK_EMPLOYEES: IEmployee[] = [
  {
    employeeId: 'EM000002',
    id: '1',
    createdAt: '2021-08-20T00:00:00.000Z',
    displayPicture: '/assets/images/faces/John.jpg',
    firstName: 'John',
    lastName: 'Doe',
    middleName: 'Michael',
    nameExtension: 'Jr.',
    birthDay: '1990-01-15',
    birthPlace: 'Cityville',
    gender: 'Male',
    civilStatus: 'Single',
    height: '175 cm',
    weight: '70 kg',
    bloodType: 'A+',
    gsisId: 'GSIS12345',
    pagibigNumber: 'PAG123',
    philhealthNumber: 'PHI456',
    sssNo: 'SSS789',
    tinNo: 'TIN123',
    agencyEmployeeNumber: 'AG123',
    citizenShip: 'US',
    residentialAddress: '123 Main St, Cityville',
    permanentAddress: '456 Oak St, Townsville',
    contact: {
      email: 'johndoe@example.com',
      phone: '555-123-4567',
      telephone: '555-987-6543',
    },
    familyBackground: {
      spouseLastname: 'Smith',
      firstName: 'Jane',
      middleName: 'Marie',
      occupation: 'Engineer',
      businessName: 'TechCorp',
      telephoneNo: '555-789-1234',
    },
    fatherName: {
      lastName: 'Doe',
      firstName: 'Robert',
      middleName: 'James',
    },
    motherName: {
      lastName: 'Doe',
      firstName: 'Mary',
      middleName: 'Ann',
    },
    civilService: {
      careerService: 'Professional',
      examinationDate: '2015-03-20',
      examinationPlace: 'Cityville',
      license: {
        number: 'CS12345',
        dateOfValidty: '2025-03-20',
      },
    },
    employeeRecord: [
      {
        startDate: '2010-01-01',
        endDate: '2015-12-31',
        position: 'Software Engineer',
        department: 'Engineering',
        monthlySalary: '5000 USD',
        salaryGrade: '10-1',
        appointmentStatus: 'Regular',
        govtService: 'Yes',
      },
      {
        startDate: '2016-01-01',
        endDate: 'Present',
        position: 'Senior Software Engineer',
        department: 'Engineering',
        monthlySalary: '6000 USD',
        salaryGrade: '11-2',
        appointmentStatus: 'Regular',
        govtService: 'Yes',
      },
    ],
    trainingProg: [
      {
        title: 'Advanced Software Development',
        startDate: '2022-04-15',
        endDate: '2022-04-30',
        hoursNo: '40 hours',
        ldType: 'In-House',
        conductedBy: 'TechCorp Training',
      },
    ],
    otherInfo: {
      specialSkills: ['JavaScript', 'React', 'Node.js'],
      recognition: ['Employee of the Month (2021)'],
      organization: ['Tech Engineers Association'],
    },
    educationalRecord: [
      {
        level: 'College',
        schoolName: 'City University',
        educationalAttainment: 'Bachelor of Science in Computer Science',
        startDate: '2010-06-01',
        endDate: '2014-05-31',
        schoolYearGraduated: '2014',
        degree: {
          major: 'Computer Science',
        },
      },
      {
        level: 'Secondary',
        schoolName: 'High School',
        educationalAttainment: 'High School Diploma',
        startDate: '2006-06-01',
        endDate: '2010-05-31',
        schoolYearGraduated: '2010',
      },
    ],
  },
  {
    employeeId: 'EM000003',
    id: '2',
    createdAt: '2021-09-20T00:00:00.000Z',
    displayPicture: '/assets/images/faces/Emily.jpg',
    firstName: 'Jane',
    lastName: 'Smith',
    middleName: 'Marie',
    nameExtension: 'Jr.',
    birthDay: '1988-08-20',
    birthPlace: 'Townsville',
    gender: 'Female',
    civilStatus: 'Married',
    height: '160 cm',
    weight: '55 kg',
    bloodType: 'B-',
    gsisId: 'GSIS54321',
    pagibigNumber: 'PAG456',
    philhealthNumber: 'PHI789',
    sssNo: 'SSS456',
    tinNo: 'TIN789',
    agencyEmployeeNumber: 'AG456',
    citizenShip: 'US',
    residentialAddress: '789 Elm St, Townsville',
    permanentAddress: '456 Oak St, Cityville',
    contact: {
      email: 'janesmith@example.com',
      phone: '555-987-6543',
      telephone: '555-123-4567',
    },
    familyBackground: {
      spouseLastname: 'Doe',
      firstName: 'John',
      middleName: 'Michael',
      occupation: 'Engineer',
      businessName: 'TechCorp',
      telephoneNo: '555-789-1234',
    },
    fatherName: {
      lastName: 'Smith',
      firstName: 'Robert',
      middleName: 'James',
    },
    motherName: {
      lastName: 'Smith',
      firstName: 'Mary',
      middleName: 'Ann',
    },
    civilService: {
      careerService: 'Professional',
      examinationDate: '2014-02-18',
      examinationPlace: 'Townsville',
      license: {
        number: 'CS54321',
        dateOfValidty: '2024-02-18',
      },
    },
    employeeRecord: [
      {
        startDate: '2012-03-01',
        endDate: '2017-02-28',
        position: 'Software Engineer',
        department: 'Engineering',
        monthlySalary: '5500 USD',
        salaryGrade: '11-1',
        appointmentStatus: 'Regular',
        govtService: 'Yes',
      },
      {
        startDate: '2017-03-01',
        endDate: 'Present',
        position: 'Senior Software Engineer',
        department: 'Engineering',
        monthlySalary: '6500 USD',
        salaryGrade: '12-1',
        appointmentStatus: 'Regular',
        govtService: 'Yes',
      },
    ],
    trainingProg: [
      {
        title: 'Advanced Software Development',
        startDate: '2021-05-15',
        endDate: '2021-05-30',
        hoursNo: '45 hours',
        ldType: 'In-House',
        conductedBy: 'TechCorp Training',
      },
    ],
    otherInfo: {
      specialSkills: ['JavaScript', 'React', 'Node.js'],
      recognition: ['Employee of the Year (2020)'],
      organization: ['Tech Engineers Association'],
    },
    educationalRecord: [
      {
        level: 'College',
        schoolName: 'Townsville University',
        educationalAttainment: 'Bachelor of Science in Computer Science',
        startDate: '2008-06-01',
        endDate: '2012-05-31',
        schoolYearGraduated: '2012',
        degree: {
          major: 'Computer Science',
        },
      },
      {
        level: 'Secondary',
        schoolName: 'Townsville High School',
        educationalAttainment: 'High School Diploma',
        startDate: '2004-06-01',
        endDate: '2008-05-31',
        schoolYearGraduated: '2008',
      },
    ],
  },
];
